# Generated by Django 3.2.8 on 2021-11-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_video_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='youtube.channel'),
        ),
    ]
