# Generated by Django 3.2.8 on 2021-11-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_alter_video_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='youtube.video'),
        ),
    ]
