# Generated by Django 3.2.8 on 2021-11-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_alter_like_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike', to='youtube.video'),
        ),
    ]
