# Generated by Django 3.2.8 on 2021-11-27 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0010_auto_20211124_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='View',
        ),
    ]
