# Generated by Django 3.2.8 on 2021-11-27 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0012_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view', to='youtube.video'),
        ),
    ]
