# Generated by Django 3.2.8 on 2021-11-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0013_alter_view_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
